blank_issues_enabled: true
contact_links:
  - name: GitHub dcm4chee-arc-light Discussions
    url: https://github.com/dcm4che/dcm4chee-arc-light/discussions
    about: Please ask and answer questions here.
  - name: dcm4che - Google Group
    url: https://groups.google.com/g/dcm4che
    about: Alternatively you may also post questions and find answers there.
